### ISSUE TITLE
Redux Middleware API

### ISSUE THREAD

**Issue by cassiozen** [cassiozen/ReactCasts#1]
Redux Middleware is an extension point that let's you insert some code that will get invoked between action dispatching, and the moment it reaches the reducer.

Redux middleware can be used for logging, crash reporting, talking to an asynchronous API, routing, and more.

Ideas for examples:
  - Log middleware
  - Persist (localstorage) middleware
  - Analytics Middleware
  - Fetch Middleware

References:
- http://blog.krawaller.se/posts/exploring-redux-middleware/

**Comment by markerikson** [comment]
Other relevant info:

- Articles on Redux middleware: https://github.com/markerikson/react-redux-links/blob/master/redux-middleware.md
- A list of almost all published Redux middlewares: https://github.com/markerikson/redux-ecosystem-links/blob/master/middleware.md

**Comment by cassiozen** [comment]
Wow, @markerikson, thanks for all the work on sharing these reference materials here and on #2 , #4 , #8 and #10 !!!

**Comment by markerikson** [comment]
Sure.  I guess I repeated myself a bit, but hopefully the info is helpful.

**Comment by cassiozen** [comment]
Live at https://www.youtube.com/watch?v=T-qtHI1qHIg

**Comment by iyn** [comment]
Just want to say that the episode was fantastic! Thank you for creating such a great content, @cassiozen!

**Comment by manpenaloza** [comment]
amazing episode, thx!
