### ISSUE TITLE
Server Side Rendering in React

### ISSUE THREAD

**Issue by neeldeep** [cassiozen/ReactCasts#11]
Explaining how server side rendering would work for react and how to configure Server Side Rendering in a React Application.

**Comment by cassiozen** [comment]
Beyond the technical aspects, I think we're current lacking an important discussion around server rendering: 
If the objective is creating a better experience for the end-user, how this compares with a React project statically hosted on a good and fast CDN network? 
Sure, in this case the client will need to fetch data, but the time-to-first-screen will be faster. At the end of the day, what makes for a better experience?

**Comment by bdougie** [comment]
It would be interesting to see how [next.js](https://zeit.co/blog/next) works as well. I wonder if rauchg is available to do a guest video on it. With that being said, I have no connection to him or zeit, but throwing it out there 😄

**Comment by cassiozen** [comment]
Yeah, awesome idea @bdougie. I think next.js deserves a whole episode.

**Comment by cassiozen** [comment]
Some more reference material:
https://www.smashingmagazine.com/2016/03/server-side-rendering-react-node-express/
https://hackernoon.com/asynchronous-server-side-rendering-with-react-3860c05f8a5e

**Comment by cassiozen** [comment]
More reference material:
https://medium.com/@kirill.konshin/react-router-redux-and-server-side-rendering-2d87d3a58cf8
https://medium.com/@benlu/ssr-with-create-react-app-v2-1b8b520681d9

**Comment by cassiozen** [comment]
Done: https://www.youtube.com/watch?v=tsEHfL-Ul1Y
