### ISSUE TITLE
Animation in react native

### ISSUE THREAD

**Issue by asifmom** [cassiozen/ReactCasts#12]

**Comment by cassiozen** [comment]
Thanks for the suggestion @asifmom. What specific kind of animations you have in mind (UI Transitions, for example)?

**Comment by pawel2105** [comment]
Since there's no info here, I'll add an opinion. Maybe go deeper with the React CSSTransitionGroup add-on.

**Comment by asifmom** [comment]
![w_4](https://cloud.githubusercontent.com/assets/492938/20754516/492d5e14-b731-11e6-81a2-2b946d74d146.gif)


In the above case, the images are dynamic and coming from server. Each fruit or object would have different weight and the scale tilt depending on the weight

**Comment by cassiozen** [comment]
Cool example, @asifmom. Can you share the source code?

**Comment by asifmom** [comment]
this is implemented in apache cordova. Interesting to see how this would be done using react-native. especially the performance and finesse of the interaction
