### ISSUE TITLE
Test Driven Development

### ISSUE THREAD

**Issue by pawel2105** [cassiozen/ReactCasts#14]
**Possible Outline**:

* Shallow intro to 1 or 2 of the main testing frameworks 
* Component testing
* Examples of feature/Integration/End-to-end testing (is that a thing in React?)
* Example of plugging tests to existing code

**References**:

* [Facebook test utils](https://facebook.github.io/react/docs/test-utils.html)
* [Rails has feature testing using rspec + capybara](https://blog.6temes.cat/introduction-to-integration-testing-with-rspec-and-capybara/)

**Comment by cassiozen** [comment]
Hi @pawel2105, thanks for the suggestion. 
My initial reaction is that Test Driven development is too big for a 5-10 minutes screencast, but there certainly is space for one (and even more) episodes covering different aspects of testing.

For additional reference, this is a very interesting article by Dave Ceddia: [Worthwhile Testing: What to Test in a React App (and Why)](http://www.codeproject.com/Articles/1153272/Worthwhile-Testing-What-to-Test-in-a-React-App-and)

**Comment by cassiozen** [comment]
I'll close this issue due to inactivity. 

Again, thanks for the suggestion, please don't feel discouraged to make further suggestions in the future because this one wasn't used.
