### ISSUE TITLE
Redux: Best way to architect reducers

### ISSUE THREAD

**Issue by cassiozen** [cassiozen/ReactCasts#2]
Suggested by user luckyleprechaun98 over Reddit (https://www.reddit.com/r/SideProject/comments/58antx/react_casts_weekly_short_videos_with_tips_tricks/)

**Comment by markerikson** [comment]
Other relevant info:

- Redux docs on "Structuring Reducers": http://redux.js.org/docs/recipes/StructuringReducers.html
- Articles on Redux architecture: https://github.com/markerikson/react-redux-links/blob/master/redux-architecture.md
