### ISSUE TITLE
Redux: Working with Derived Data & Selectors

### ISSUE THREAD

**Issue by zsherman** [cassiozen/ReactCasts#20]
https://github.com/reactjs/reselect provides a convenient way of caching data with redux, some explanation and examples would be nice.

**Comment by cassiozen** [comment]
Thanks for the suggestion. I guess reselect is a topic only really understood by developers who already understand selectors (and how to deal with derived data in general on Redux...).
So, now this gave me the idea of an episode on derived data and selectors (that could also include infos on reselect).

What do you think?

**Comment by zsherman** [comment]
sounds like a great idea!

**Comment by cassiozen** [comment]
Perfect, this is now planned for production.

**Comment by cassiozen** [comment]
Reference Material:

https://github.com/Automattic/wp-calypso/blob/master/docs/our-approach-to-data.md#selectors

https://engineering.haus.com/so-youve-screwed-up-your-redux-store-or-why-redux-makes-refactoring-easy-400e19606c71#.cydl69bim

https://medium.com/@benipsen/seven-months-into-redux-two-things-my-team-learned-along-the-way-5d979c25ea61#f316

http://www.thinkloop.com/article/extreme-decoupling-react-redux-selectors/

**Comment by cassiozen** [comment]
Live at https://www.youtube.com/watch?v=frT3to2ACCw
