### ISSUE TITLE
Gist in FAQ leads to 404

### ISSUE THREAD

**Issue by budda** [cassiozen/ReactCasts#24]
- Do you want to *Request a Screencast* or report a *bug*?
Bug

- If you're reporting bug, please provide the steps to reproduce.
Go to https://github.com/cassiozen/ReactCasts/wiki/FAQ click the Gist link about atom's user CSS.
Should it be linking to https://gist.github.com/cassiozen/d1011664f4afc7a3e5004e65e9b35a8d ?

    - Also, please mention your browser and operating system version.
Chrome, OSX.

**Comment by cassiozen** [comment]
Thanks for reporting. The link is now fixed.
