### ISSUE TITLE
Undo/Redo in Redux

### ISSUE THREAD

**Issue by rayetzki** [cassiozen/ReactCasts#27]
Hey, could you please make a video about Redux Undo/Redo . Been stuck with it.

**Comment by cassiozen** [comment]
Awesome idea. What are you trying to achieve, Debugging?

**Comment by kastsiushkin** [comment]
@lil-chipmunk if you are using or considering to start using `redux-saga` take a look at the last recipe [here](http://yelouafi.github.io/redux-saga/docs/recipes/index.html) for some ideas.

**Comment by lil-chipmunk** [comment]
@cassiozen basic concepts and usage (where can i apply it) :)
