### ISSUE TITLE
Config setup for development/production

### ISSUE THREAD

**Issue by kastsiushkin** [cassiozen/ReactCasts#28]
This could be a broad topic, but here is a list of things I had in mind:

- setup a config with dev/staging/prod constants (i.e. API root url, emails, etc)
- setup Webpack to use appropriate config upon each build (based on ENV variable)
- use the config constants in the app
Bonus: review options for fetching data (fetchAPI, superagent, bluebird, etc)

I specifically looking for a clean way to organize my API layer and upon dev/staging/prod build use  appropriate URLs.

Thank you

**Comment by kasiriveni** [comment]
:+1:

**Comment by feritarslan** [comment]
👍
