### ISSUE TITLE
Redux-saga

### ISSUE THREAD

**Issue by zsherman** [cassiozen/ReactCasts#29]
Have been digging into redux-saga a bit and it can be a little hard to wrap your mind around at first. I think a screencast on this would be pretty helpful.

**Comment by cassiozen** [comment]
Cool, thanks for the suggestion. Any reference materials you are aware of?

**Comment by zsherman** [comment]
The redux-saga docs themselves are pretty good http://yelouafi.github.io/redux-saga/, I've also found a few scattered articles:

- https://riadbenguella.com/2016/01/20/how-es6-generators-are-changing-the-way-we-write-javascript/
- http://jaysoo.ca/2016/01/03/managing-processes-in-redux-using-sagas/
- http://konkle.us/master-complex-redux-workflows-with-sagas/
