### ISSUE TITLE
Feed to follow new casts?

### ISSUE THREAD

**Issue by alexilyaev** [cassiozen/ReactCasts#31]
Hi guys,

I really like the ReactCasts episodes, would be nice if there was a feed I can follow to be notified of new episodes.

Ideally some RSS feed or email subscription.
Or at least, if you'd use a proper git release tag for each episode added, I can hook up to that.

Thanks!

**Comment by cassiozen** [comment]
Hi @alexilyaev - I'm glad you like it!

I can totally start tagging when pushing new episodes. You can also receive email notifications directly from youtube when new episodes are uploaded: Subscribe to the channel and click the "Bell" icon (it's not on by default... You have to check it).

![subs notif](https://cloud.githubusercontent.com/assets/33676/21462219/8e213114-c940-11e6-84f5-0f0596a674b6.jpg)

**Comment by alexilyaev** [comment]
Thanks, the tags will be great.
About YouTube subscriptions, since I have so many, I filter them into a label in Gmail, which I don't check often, since most of them are just funny stuff :-).
