### ISSUE TITLE
Creating reusable components

### ISSUE THREAD

**Issue by metasean** [cassiozen/ReactCasts#38]
In relation to request #22 "React in Production / Large App Overview", it would be interesting to see how you construct and deploy individual components that are reusable across applications (e.g. npm modules, but could be linked or included in other ways).

Of particular interest, most component tutorials I have seen have not acknowledged potential isomorphic/universal usage.

**Comment by cassiozen** [comment]
I really like this idea. Do you have any examples, articles or other source material that you came across to share?
