### ISSUE TITLE
Introduction to `styled-components`

### ISSUE THREAD

**Issue by arosenb2** [cassiozen/ReactCasts#40]
Request a Screencast
I've seen a lot of the community talk about `styled-components`. Can you give an intro to that? 
- [Article announcing v2 of `styled-components`](https://medium.com/styled-components/announcing-v2-f01ef3766ac2)
- [Library Home Page](https://www.styled-components.com/)

Thanks! Looking forward to seeing what you cover on this!

**Comment by cassiozen** [comment]
Thanks for the suggestion. Yeah, I think a "styles" related episode is long due...
