### ISSUE TITLE
Episode 7 - error in hot reload

### ISSUE THREAD

**Issue by iloveyii** [cassiozen/ReactCasts#55]
- Clone the repo
- Try to run episode7, so cd to episode7
- Run npm install 
- npm start : gives the following error:

Failed to compile.

Error in multi main
Module not found: 'react-hot' in /home/alex/projects/frontend/ReactCasts/episode7/hrm-with-react-hot-loader

 @ multi main

**Comment by CodeVoyager** [comment]
Try changing  'react-hot' to  'react-hot-loader'.
