### ISSUE TITLE
React Native over-the-air updates

### ISSUE THREAD

**Issue by cassiozen** [cassiozen/ReactCasts#6]
Talk about strategies for dynamic updating JavaScript in React Native Applications.

References:
- [AeroFS's Auto Updater](https://github.com/aerofs/react-native-auto-updater)
- [Microsoft's CodePush](http://microsoft.github.io/code-push/)

**Comment by neeldeep** [comment]
Adding one more for Reference,
Electrode Over the Air Server from Walmart Labs [http://www.electrode.io/docs/electrode_react_native_over_the_air_electron.html](url)

**Comment by cassiozen** [comment]
Thanks!
