### ISSUE TITLE
Episode on proper testing of Redux actions / reducers / selectors

### ISSUE THREAD

**Issue by linuxhype** [cassiozen/ReactCasts#62]
Would love an episode on best-practices and libraries used in testing React Redux applications using things like Jest, Mocha / Chai or similar.

It could be a general episode on testing React applications with just a section of redux, but I would personally appreciate focus on testing Action handlers and reducers in redux apps!

Thanks and keep up the great work!

**Comment by dindonus** [comment]
Hey hey 👋
Great idea! I would love it too. 
And thanks for your awesome ✨ chanel.
