### ISSUE TITLE
Create build (deploy online)

### ISSUE THREAD

**Issue by alinirabi** [cassiozen/ReactCasts#63]
for create build for online
- npm run build
what i have to add to the scripts

"scripts": {
    "start": "if-env NODE_ENV=production && npm run start:prod || npm run start:dev",
    "start:dev": "webpack-dev-server --inline --content-base public/ --history-api-fallback",
    "start:prod": "webpack && node server.js"
  },

thanks in advanced

**Comment by LBWright** [comment]
@cassiozen Help still wanted on this issue? I can make a quick build script and make a PR if so.
