### ISSUE TITLE
Why have you stopped to record videos on react casts?

### ISSUE THREAD

**Issue by rrfaria** [cassiozen/ReactCasts#69]
First of all, the react Casts was the most important in my career with react and I really thank you for that.
Now I would like to know why have you stopped with react casts ? the casts was amazing and should continue

I hope you think about that ... thanks

**Comment by cassiozen** [comment]
Thanks a lot, comments like this make my day. I'm back, I wrote about it here: https://twitter.com/cassiozen/status/1344550170831310848?s=21
