### ISSUE TITLE
Big / Complex forms in React

### ISSUE THREAD

**Issue by cassiozen** [cassiozen/ReactCasts#8]
Controlled form components are great for small forms, but what about the really big and complex forms? How to deal with validation? Which are the performance issues (if any)?

**Comment by markerikson** [comment]
Other relevant info:

- Articles on React forms: https://github.com/markerikson/react-redux-links/blob/master/react-forms.md
- Articles on React performance: https://github.com/markerikson/react-redux-links/blob/master/react-performance.md

**Comment by iyn** [comment]
Some topic worth exploring:
- wizard-type forms and complex transition between steps (e.g going from step A to B may require async validaiton and/or communication with API to get some data)
- reusing validation and different widgets

**Comment by markerikson** [comment]
I highly recommend @goshakkk 's recent posts on React and forms, which can be found at http://goshakkk.name/on-react/ .  He also had great advice in this recent Reddit thread: https://www.reddit.com/r/reactjs/comments/5gamph/how_do_you_guys_handle_complex_forms_with/ .

**Comment by cassiozen** [comment]
Also: https://goshakkk.name/instant-form-fields-validation-react/
